#!/usr/bin/env sh

# Check if the file exists
if [[ ! -f "./mypackages.txt" ]]; then
    echo "Error: packages-list.txt file not found!"
    exit 1
fi

# Read the file and install each package
while IFS= read -r app; do
    echo "[+] Installing $app"
    doas pacman --noconfirm -S "$app"
done < "./mypackages.txt"
