#!/usr/bin/env bash 

FILE="./myarchpackages.txt"

# Check if the file exists
if [ ! -f "$FILE" ]; then
    echo "Error: $FILE file not found!"
    exit 1
fi

# Read the file and install each package
while IFS= read -r app; do
    echo "[+] Installing $app"
    doas pacman --noconfirm -S "$app"
done < "$FILE"
